### PR TITLE
refactor: capitalize immutable variables

### PR DESCRIPTION
**Pull request by andreivladbrg**
Depends on https://github.com/sablier-labs/v2-periphery/pull/198

Closes https://github.com/sablier-labs/v2-periphery/issues/199

Note: being a small change I think this shouldn't be included in the `CHANGELOG` .

### CODE REVIEW

**Comment by PaulRBerg** [comment]
@andreivladbrg can you rebase from `main` please

In the future, consider branching off from `main` (`git checkout -b NEW_BRANCH main`) so that PRs don't depend on each other.

**Comment by andreivladbrg** [comment]
But my intention was to depend on that PR 😅

This way I avoided potential conflicts.

**Comment by PaulRBerg** [comment]
> This way I avoided potential conflicts.

There were no _actual_ conflicts between these two PRs. And this can often be inferred between two small PRs.

**Review by PaulRBerg — CHANGES_REQUESTED** [review]
LGTM except for the `_original` immutable var in `OnlyDelegateCall`, which also has to be modified.

**Comment by andreivladbrg** [comment]
> There were no actual conflicts between these two PRs. And this can often be inferred between two small PRs.

Yes there would have been conflicts, in the `.gitmodules` file. A small one, but still a conflict. It does not matter the size of a PR, for me is a good heurstic to prevent any potential conflict.

> LGTM except for the _original immutable var in OnlyDelegateCall, which also has to be modified.

Correct, pushed a commit now

**Comment by PaulRBerg** [comment]
> for me is a good heurstic to prevent any potential conflict.

Fair enough

**Review by PaulRBerg — APPROVED** [review]
looks good now.

We will have to announce this PR in the changelog because the ABI has changed in the `ProxyPlugin` - `archive` is now `ARCHIVE`.

**Pull request merged**
