### PR TITLE
refactor: LockupLL to LL and LockupLT to LT

### LINKED ISSUE #319: Rename "LockupLL" to "LL" and "LockupLT" to "LT"
See context in https://github.com/sablier-labs/v2-periphery/discussions/314.

### PR DESCRIPTION
**Pull request by smol-ninja**
closes #319

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Could you please re-do the work on this PR after #324 gets merged?

It might be easier to start from scratch than fix the git conflicts in my PR.

**Review by PaulRBerg — APPROVED** [review]
lgtm except that we will merge this after #324 gets merged

**Comment by smol-ninja** [comment]
Yes. I am re-doing it with prb-feedback changes.

**Comment by smol-ninja** [comment]
@PaulRBerg can you please give it a quick review in case I haven't missed anything?

**Review by PaulRBerg — APPROVED** [review]
top

**Pull request merged**
