### PR TITLE
Rename create functions to match V2 core

### PR DESCRIPTION
**Pull request by smol-ninja**
Closes https://github.com/sablier-labs/v2-periphery/issues/263

### Requirements for passing ALL tests

- [x] https://github.com/sablier-labs/v2-core/pull/798 to be merged first
- [x] Update precompiles in v2-core
- [x] Update v2-core version in package.json https://github.com/sablier-labs/v2-periphery/blob/0925e93cc1da5bf3602de4424712109f967bb4a9/package.json#L15
- [ ] v2-core to be deployed on mainnet for fork testing

### CODE REVIEW

**Comment by andreivladbrg** [comment]
i think this PR is going to be on hold, since we release a new NPM version

@PaulRBerg should we have NPM releases more often which should be marked as "beta" e.g. 1.1.3-b?

**Comment by PaulRBerg** [comment]
Good point about the NPM version, @andreivladbrg.

> should we have NPM releases more often which should be marked as "beta" e.g. 1.1.3-b?

Nope. We can simply install V2 Core from GitHub:

```json
"@sablier/v2-core": "github:sablier-labs/v2-core#staging"
```

**Comment by andreivladbrg** [comment]
> Nope. We can simply install V2 Core from GitHub:

correct, forgot that it now works because of the `bun install` CLI ran before, it used to not work due to [pre-pack](https://github.com/sablier-labs/v2-core/blob/7819a3b5122036596edff3326b97a8c03750bbb8/package.json#L70)

**Comment by andreivladbrg** [comment]
@smol-ninja merged the PR on `staging` and updated the precompiles, you can update this branch PR too

regarding the fork tests, you can temporarily deploy the core contracts and comment this line:

https://github.com/sablier-labs/v2-periphery/blob/d3550295c650d270c204e84b7997c9751e289149/test/fork/Fork.t.sol#L35

**Comment by smol-ninja** [comment]
> you can temporarily deploy the core contracts and comment this line:

@andreivladbrg Sorry but I didn't get what you meant by this. Do you mean deploying the staging branch on the mainnet? And how does commenting on that line help?

**Comment by andreivladbrg** [comment]
> Sorry but I didn't get what you meant by this. Do you mean deploying the staging branch on the mainnet? And how does commenting on that line help?

ah, no no, poor wording on my side

we just need to do the same thing as in the `Integration_Test`  contract:

https://github.com/sablier-labs/v2-periphery/blob/d3550295c650d270c204e84b7997c9751e289149/test/integration/Integration.t.sol#L39-L41

**Comment by smol-ninja** [comment]
@andreivladbrg can you please have a last look at this and suggest or approve changes?

**Review by andreivladbrg — APPROVED** [review]
LGTM

just one small miss:

https://github.com/sablier-labs/v2-periphery/blob/c686264d8dd572a8a1494b3f14660b6307d58c31/test/Base.t.sol#L139

**Pull request merged**
